#set up properties
PROJECT_ID: qwiklabs-gcp-01-b5aec878831c

server:
    port: ${DEFAULT_PORT:9000}

spring:
    application:
        name: app-spanner
    cloud:
        config:
            namespace: default
            enabled: true
            name: Cloud
            profile: dev, cloud, spanner
            label: master
        gcp:
            credentials:
                location: classpath:key.json
            project-id: ${PROJECT_ID:qwiklabs-gcp-01-b5aec878831c}
            spanner:
                 instance-id: ${INSTANCE_ID:marketplace-db}
                 database: ${DATASET_NAME:marketplace}