#set up properties
PROJECT_ID: qwiklabs-gcp-02-4d72956ea6cf

server:
    port: ${DEFAULT_PORT:80}

spring:
    application:
        name: app-spanner
    cloud:
        config:
            namespace: default
            enabled: true
            name: Cloud
            profile: dev, cloud, spanner
            label: master
        gcp:
            project-id: ${PROJECT_ID:qwiklabs-gcp-02-4d72956ea6cf}
            credentials:
                location: classpath:key.json
            spanner:
                 instance-id: ${INSTANCE_ID}
                 database: ${DATASET_NAME:marketplace}